# Lotus Per-App Configuration
# 0 = Off, 1 = Uinput (Smooth), 2 = Uinput (Slow), 3 = Uinput (Hardcore), 4 = Surrounding Text, 5 = Preedit, 6 = Emoji Picker
kitty=3
jetbrains-idea=3
jetbrains-datagrip=3
helium=2
jetbrains-webstorm=3
dev.zed.Zed=3
Thorium_Browser=4
