# Main colors
background            #131313
foreground            #e2e2e2
cursor                #e2e2e2
cursor_text_color     #131313
selection_background  #364955
selection_foreground  #d1e5f4
url_color             #cac1ea

# ANSI colors
color0                #131313
color1                #ffb4ab
color2                #cac1ea
color3                #b5c9d7
color4                #7bd0ff
color5                #cac1ea
color6                #b5c9d7
color7                #e2e2e2
color8                #474747
color9                #93000a
color10               #484264
color11               #364955
color12               #004c69
color13               #364955
color14               #484264
color15               #c6c6c6

# Starship prompt bubbles
color255              #004c69
color254              #7bd0ff
color253              #364955
color252              #b5c9d7
color251              #484264
color250              #cac1ea
color249              #93000a
color248              #ffb4ab
color232              #c4e7ff
color233              #003549
color234              #d1e5f4
color235              #20333e
color236              #e6deff
color237              #322c4c
color238              #ffdad6
color239              #690005
color240              #c4e7ff
color243              #7bd0ff
color244              #ffb4ab
color245              #474747

# UI elements
active_tab_foreground   #003549
active_tab_background   #7bd0ff
inactive_tab_foreground #c4e7ff
inactive_tab_background #004c69
active_border_color     #7bd0ff
inactive_border_color   #919191

# Marks
mark1_foreground        #001e2c
mark1_background        #c4e7ff
mark2_foreground        #0a1e28
mark2_background        #d1e5f4
mark3_foreground        #1d1736
mark3_background        #e6deff
