# Matugen template for btop

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal:
# "#RRGGBB", "#BW" or "0-255 0-255 0-255".

# Main background must remain empty for terminal transparency.
theme[main_bg]=""
theme[main_fg]="#e2e2e2"
theme[title]="#7bd0ff"
theme[hi_fg]="#b5c9d7"
theme[selected_bg]="#7bd0ff"
theme[selected_fg]="#003549"
theme[inactive_fg]="#c6c6c6"
theme[proc_misc]="#cac1ea"

theme[cpu_box]="#919191"
theme[mem_box]="#919191"
theme[net_box]="#919191"
theme[proc_box]="#919191"
theme[div_line]="#474747"

theme[temp_start]="#b5c9d7"
theme[temp_mid]="#7bd0ff"
theme[temp_end]="#ffb4ab"

theme[cpu_start]="#b5c9d7"
theme[cpu_mid]="#7bd0ff"
theme[cpu_end]="#ffb4ab"

theme[free_start]="#b5c9d7"
theme[free_mid]=""
theme[free_end]="#364955"

theme[cached_start]="#cac1ea"
theme[cached_mid]=""
theme[cached_end]="#484264"

theme[available_start]="#7bd0ff"
theme[available_mid]=""
theme[available_end]="#004c69"

theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

theme[download_start]="#b5c9d7"
theme[download_mid]="#7bd0ff"
theme[download_end]="#cac1ea"

theme[upload_start]="#b5c9d7"
theme[upload_mid]="#7bd0ff"
theme[upload_end]="#cac1ea"
